package com.unis.dao.mybatis;

import org.springframework.stereotype.Repository;

import com.unis.model.Admin;

@Repository
public interface AdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	Admin selectByPrimaryKey(String name);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_backend_admin
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Admin record);
}