package com.unis.dao.mybatis;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.unis.model.AppConfig;

@Repository
public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    AppConfig selectByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppConfig record);
    List<AppConfig> selectAll();
}