package com.unis.dao.mybatis;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.unis.model.ChannelConfig;

@Repository
public interface ChannelConfigMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	int insert(ChannelConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	int insertSelective(ChannelConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	ChannelConfig selectByPrimaryKey(Integer channelId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ChannelConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_channel_config
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ChannelConfig record);

	List<ChannelConfig> selectAll();
}