package com.unis.dao.mybatis;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.unis.model.User;
import com.unis.model.json_model.UserSelect;

@Repository
public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	User selectByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(User record);

	List<User> selectByUserSelect(UserSelect select);
    
    Integer countByUserSelect(UserSelect select);
    
    int releaseFreezenBalance(@Param("reduce")double reduce,@Param("account")String account);
    Double sum_withdraw(@Param("channel") int channel);
    Double sum_recharge(@Param("channel") int channel); 
    Integer countMobileUser(@Param("channel") int channel);
    Double sum_balance(@Param("channel") int channel);
    Double sum_extract_balance(@Param("channel") int channel);
    
    
}