package com.unis.model;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_backend_admin.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_backend_admin.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_backend_admin.pages
	 * @mbg.generated
	 */
	private String pages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_backend_admin.channels
	 * @mbg.generated
	 */
	private String channels;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_backend_admin.name
	 * @return  the value of t_backend_admin.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_backend_admin.name
	 * @param name  the value for t_backend_admin.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_backend_admin.password
	 * @return  the value of t_backend_admin.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_backend_admin.password
	 * @param password  the value for t_backend_admin.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_backend_admin.pages
	 * @return  the value of t_backend_admin.pages
	 * @mbg.generated
	 */
	public String getPages() {
		return pages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_backend_admin.pages
	 * @param pages  the value for t_backend_admin.pages
	 * @mbg.generated
	 */
	public void setPages(String pages) {
		this.pages = pages == null ? null : pages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_backend_admin.channels
	 * @return  the value of t_backend_admin.channels
	 * @mbg.generated
	 */
	public String getChannels() {
		return channels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_backend_admin.channels
	 * @param channels  the value for t_backend_admin.channels
	 * @mbg.generated
	 */
	public void setChannels(String channels) {
		this.channels = channels == null ? null : channels.trim();
	}
}