package com.unis.model;

import java.util.Date;

public class AppInfo extends AppInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.channel_name
	 * @mbg.generated
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.player_count
	 * @mbg.generated
	 */
	private Integer playerCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.icon_url
	 * @mbg.generated
	 */
	private String iconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.game_url
	 * @mbg.generated
	 */
	private String gameUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.target
	 * @mbg.generated
	 */
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.order_flag
	 * @mbg.generated
	 */
	private Integer orderFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.in_channel
	 * @mbg.generated
	 */
	private String inChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.create_time
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.id
	 * @return  the value of t_app_info.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.id
	 * @param id  the value for t_app_info.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.channel_name
	 * @return  the value of t_app_info.channel_name
	 * @mbg.generated
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.channel_name
	 * @param channelName  the value for t_app_info.channel_name
	 * @mbg.generated
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName == null ? null : channelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.title
	 * @return  the value of t_app_info.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.title
	 * @param title  the value for t_app_info.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.player_count
	 * @return  the value of t_app_info.player_count
	 * @mbg.generated
	 */
	public Integer getPlayerCount() {
		return playerCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.player_count
	 * @param playerCount  the value for t_app_info.player_count
	 * @mbg.generated
	 */
	public void setPlayerCount(Integer playerCount) {
		this.playerCount = playerCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.icon_url
	 * @return  the value of t_app_info.icon_url
	 * @mbg.generated
	 */
	public String getIconUrl() {
		return iconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.icon_url
	 * @param iconUrl  the value for t_app_info.icon_url
	 * @mbg.generated
	 */
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl == null ? null : iconUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.game_url
	 * @return  the value of t_app_info.game_url
	 * @mbg.generated
	 */
	public String getGameUrl() {
		return gameUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.game_url
	 * @param gameUrl  the value for t_app_info.game_url
	 * @mbg.generated
	 */
	public void setGameUrl(String gameUrl) {
		this.gameUrl = gameUrl == null ? null : gameUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.target
	 * @return  the value of t_app_info.target
	 * @mbg.generated
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.target
	 * @param target  the value for t_app_info.target
	 * @mbg.generated
	 */
	public void setTarget(String target) {
		this.target = target == null ? null : target.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.status
	 * @return  the value of t_app_info.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.status
	 * @param status  the value for t_app_info.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.order_flag
	 * @return  the value of t_app_info.order_flag
	 * @mbg.generated
	 */
	public Integer getOrderFlag() {
		return orderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.order_flag
	 * @param orderFlag  the value for t_app_info.order_flag
	 * @mbg.generated
	 */
	public void setOrderFlag(Integer orderFlag) {
		this.orderFlag = orderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.in_channel
	 * @return  the value of t_app_info.in_channel
	 * @mbg.generated
	 */
	public String getInChannel() {
		return inChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.in_channel
	 * @param inChannel  the value for t_app_info.in_channel
	 * @mbg.generated
	 */
	public void setInChannel(String inChannel) {
		this.inChannel = inChannel == null ? null : inChannel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.description
	 * @return  the value of t_app_info.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.description
	 * @param description  the value for t_app_info.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.update_time
	 * @return  the value of t_app_info.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.update_time
	 * @param updateTime  the value for t_app_info.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.create_time
	 * @return  the value of t_app_info.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.create_time
	 * @param createTime  the value for t_app_info.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}