package com.unis.model;

public class AppInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.channel_id
	 * @mbg.generated
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_info.app_id
	 * @mbg.generated
	 */
	private Integer appId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.channel_id
	 * @return  the value of t_app_info.channel_id
	 * @mbg.generated
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.channel_id
	 * @param channelId  the value for t_app_info.channel_id
	 * @mbg.generated
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_info.app_id
	 * @return  the value of t_app_info.app_id
	 * @mbg.generated
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_info.app_id
	 * @param appId  the value for t_app_info.app_id
	 * @mbg.generated
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}
}