package com.unis.model;

import java.util.Date;

public class ChannelConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.channel_id
	 * @mbg.generated
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.channel_key
	 * @mbg.generated
	 */
	private String channelKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.coin_name
	 * @mbg.generated
	 */
	private String coinName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.exchange_rate
	 * @mbg.generated
	 */
	private Integer exchangeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.channel_name
	 * @mbg.generated
	 */
	private String channelName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.official_account
	 * @mbg.generated
	 */
	private String officialAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.off_account_pwd
	 * @mbg.generated
	 */
	private String offAccountPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.min_in_value
	 * @mbg.generated
	 */
	private Integer minInValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.min_out_value
	 * @mbg.generated
	 */
	private Integer minOutValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.max_out_value
	 * @mbg.generated
	 */
	private Integer maxOutValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_channel_config.url
	 * @mbg.generated
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.channel_id
	 * @return  the value of t_channel_config.channel_id
	 * @mbg.generated
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.channel_id
	 * @param channelId  the value for t_channel_config.channel_id
	 * @mbg.generated
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.id
	 * @return  the value of t_channel_config.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.id
	 * @param id  the value for t_channel_config.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.channel_key
	 * @return  the value of t_channel_config.channel_key
	 * @mbg.generated
	 */
	public String getChannelKey() {
		return channelKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.channel_key
	 * @param channelKey  the value for t_channel_config.channel_key
	 * @mbg.generated
	 */
	public void setChannelKey(String channelKey) {
		this.channelKey = channelKey == null ? null : channelKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.coin_name
	 * @return  the value of t_channel_config.coin_name
	 * @mbg.generated
	 */
	public String getCoinName() {
		return coinName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.coin_name
	 * @param coinName  the value for t_channel_config.coin_name
	 * @mbg.generated
	 */
	public void setCoinName(String coinName) {
		this.coinName = coinName == null ? null : coinName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.exchange_rate
	 * @return  the value of t_channel_config.exchange_rate
	 * @mbg.generated
	 */
	public Integer getExchangeRate() {
		return exchangeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.exchange_rate
	 * @param exchangeRate  the value for t_channel_config.exchange_rate
	 * @mbg.generated
	 */
	public void setExchangeRate(Integer exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.channel_name
	 * @return  the value of t_channel_config.channel_name
	 * @mbg.generated
	 */
	public String getChannelName() {
		return channelName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.channel_name
	 * @param channelName  the value for t_channel_config.channel_name
	 * @mbg.generated
	 */
	public void setChannelName(String channelName) {
		this.channelName = channelName == null ? null : channelName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.official_account
	 * @return  the value of t_channel_config.official_account
	 * @mbg.generated
	 */
	public String getOfficialAccount() {
		return officialAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.official_account
	 * @param officialAccount  the value for t_channel_config.official_account
	 * @mbg.generated
	 */
	public void setOfficialAccount(String officialAccount) {
		this.officialAccount = officialAccount == null ? null : officialAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.off_account_pwd
	 * @return  the value of t_channel_config.off_account_pwd
	 * @mbg.generated
	 */
	public String getOffAccountPwd() {
		return offAccountPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.off_account_pwd
	 * @param offAccountPwd  the value for t_channel_config.off_account_pwd
	 * @mbg.generated
	 */
	public void setOffAccountPwd(String offAccountPwd) {
		this.offAccountPwd = offAccountPwd == null ? null : offAccountPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.min_in_value
	 * @return  the value of t_channel_config.min_in_value
	 * @mbg.generated
	 */
	public Integer getMinInValue() {
		return minInValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.min_in_value
	 * @param minInValue  the value for t_channel_config.min_in_value
	 * @mbg.generated
	 */
	public void setMinInValue(Integer minInValue) {
		this.minInValue = minInValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.min_out_value
	 * @return  the value of t_channel_config.min_out_value
	 * @mbg.generated
	 */
	public Integer getMinOutValue() {
		return minOutValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.min_out_value
	 * @param minOutValue  the value for t_channel_config.min_out_value
	 * @mbg.generated
	 */
	public void setMinOutValue(Integer minOutValue) {
		this.minOutValue = minOutValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.max_out_value
	 * @return  the value of t_channel_config.max_out_value
	 * @mbg.generated
	 */
	public Integer getMaxOutValue() {
		return maxOutValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.max_out_value
	 * @param maxOutValue  the value for t_channel_config.max_out_value
	 * @mbg.generated
	 */
	public void setMaxOutValue(Integer maxOutValue) {
		this.maxOutValue = maxOutValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.update_time
	 * @return  the value of t_channel_config.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.update_time
	 * @param updateTime  the value for t_channel_config.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.create_time
	 * @return  the value of t_channel_config.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.create_time
	 * @param createTime  the value for t_channel_config.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_channel_config.url
	 * @return  the value of t_channel_config.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_channel_config.url
	 * @param url  the value for t_channel_config.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}