package com.unis.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.account
	 * @mbg.generated
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.access_token
	 * @mbg.generated
	 */
	private String accessToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.display_name
	 * @mbg.generated
	 */
	private String displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.mobile
	 * @mbg.generated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.channel
	 * @mbg.generated
	 */
	private Integer channel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.channel_account
	 * @mbg.generated
	 */
	private String channelAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.balance
	 * @mbg.generated
	 */
	private Double balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.extract_balance
	 * @mbg.generated
	 */
	private Double extractBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.active_days
	 * @mbg.generated
	 */
	private Integer activeDays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sum_recharge
	 * @mbg.generated
	 */
	private Double sumRecharge;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.account
	 * @return  the value of t_user.account
	 * @mbg.generated
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.account
	 * @param account  the value for t_user.account
	 * @mbg.generated
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.access_token
	 * @return  the value of t_user.access_token
	 * @mbg.generated
	 */
	public String getAccessToken() {
		return accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.access_token
	 * @param accessToken  the value for t_user.access_token
	 * @mbg.generated
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken == null ? null : accessToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.display_name
	 * @return  the value of t_user.display_name
	 * @mbg.generated
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.display_name
	 * @param displayName  the value for t_user.display_name
	 * @mbg.generated
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName == null ? null : displayName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.mobile
	 * @return  the value of t_user.mobile
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.mobile
	 * @param mobile  the value for t_user.mobile
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.channel
	 * @return  the value of t_user.channel
	 * @mbg.generated
	 */
	public Integer getChannel() {
		return channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.channel
	 * @param channel  the value for t_user.channel
	 * @mbg.generated
	 */
	public void setChannel(Integer channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.channel_account
	 * @return  the value of t_user.channel_account
	 * @mbg.generated
	 */
	public String getChannelAccount() {
		return channelAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.channel_account
	 * @param channelAccount  the value for t_user.channel_account
	 * @mbg.generated
	 */
	public void setChannelAccount(String channelAccount) {
		this.channelAccount = channelAccount == null ? null : channelAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.balance
	 * @return  the value of t_user.balance
	 * @mbg.generated
	 */
	public Double getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.balance
	 * @param balance  the value for t_user.balance
	 * @mbg.generated
	 */
	public void setBalance(Double balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.extract_balance
	 * @return  the value of t_user.extract_balance
	 * @mbg.generated
	 */
	public Double getExtractBalance() {
		return extractBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.extract_balance
	 * @param extractBalance  the value for t_user.extract_balance
	 * @mbg.generated
	 */
	public void setExtractBalance(Double extractBalance) {
		this.extractBalance = extractBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.status
	 * @return  the value of t_user.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.status
	 * @param status  the value for t_user.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.update_time
	 * @return  the value of t_user.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.update_time
	 * @param updateTime  the value for t_user.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_time
	 * @return  the value of t_user.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_time
	 * @param createTime  the value for t_user.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.active_days
	 * @return  the value of t_user.active_days
	 * @mbg.generated
	 */
	public Integer getActiveDays() {
		return activeDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.active_days
	 * @param activeDays  the value for t_user.active_days
	 * @mbg.generated
	 */
	public void setActiveDays(Integer activeDays) {
		this.activeDays = activeDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.sum_recharge
	 * @return  the value of t_user.sum_recharge
	 * @mbg.generated
	 */
	public Double getSumRecharge() {
		return sumRecharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.sum_recharge
	 * @param sumRecharge  the value for t_user.sum_recharge
	 * @mbg.generated
	 */
	public void setSumRecharge(Double sumRecharge) {
		this.sumRecharge = sumRecharge;
	}

}